### ISSUE TITLE
dimensions-0.3.0.0 fails its test suite

### ISSUE THREAD

**Issue by peti** [achirkin/fasttensor#1]
Citing from https://nix-cache.s3.amazonaws.com/log/bva35jjj8g57dp80cxd0ds11x76msq16-dimensions-0.3.0.0.drv:

~~~
Running 1 test suites...
Test suite dimensions-test: RUNNING...
Prelude.read: no parse
~~~~

**Comment by achirkin** [comment]
Thanks for pointing me to this! I've never used nix, but it works using stack or stock cabal.
However, I've found [a question on stackoverflow](https://stackoverflow.com/questions/39310043/getting-prelude-read-no-parse-error-when-using-detailed-0-9-tests-with-cabal) that is, probably, related.
They refer to a [PR](https://github.com/haskell/cabal/pull/3527) to cabal that, hopefully, fixes it.

I guess, the workaround is to force compile library static:
`cabal configure --enable-tests --disable-shared`.
Maybe a good combination of ghc-options would solve this, but I cannot test it.

**Comment by peti** [comment]
Well, compiling the library statically is a rather intrusive change. Also, I don't think that this issue is related to Nix. The ticket suggests that it is related to compiling with dynamic linking enabled.

**Comment by achirkin** [comment]
Hopefully, fixed that by changing tests type back to `exitcode-stdio-1.0`.
