### ISSUE TITLE
Add mechanism for easily getting field offsets

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/fasttensor#13]
I'm not really sure how this would work, exactly, but it seems like there should be some mechanism for easily getting the offset of a field in a PrimBytes instance.  In my code I have this:

```hs
data Vertex =
  Vertex {
    vtxPos :: Vec3f,
    vtxColor :: Vec3f,
    vtxTexCoord :: Vec2f
  } deriving (Eq, Show, Generic)

instance PrimBytes Vertex

vertexAttributeDescriptionsAt :: Word32 -> [VkVertexInputAttributeDescription]
vertexAttributeDescriptionsAt binding =
  createVk @VkVertexInputAttributeDescription <$> [
    set @"binding" binding &*
    set @"location" 0 &*
    set @"format" VK_FORMAT_R32G32B32_SFLOAT &*
    set @"offset" 0,

    set @"binding" binding &*
    set @"location" 1 &*
    set @"format" VK_FORMAT_R32G32B32_SFLOAT &*
    set @"offset" offset1,

    set @"binding" binding &*
    set @"location" 2 &*
    set @"format" VK_FORMAT_R32G32_SFLOAT &*
    set @"offset" offset2
  ]
  where
    offset1 = fromIntegral (sizeOf $ vtxPos undefined)
    offset2 = offset1 + fromIntegral (sizeOf $ vtxColor undefined)
```

It'd be nice if I could just say something like `offsetOf @"vtxColor"`.  (And for that matter, why not `sizeOf @"vtxColor"` ~~or just `sizeOf @Vec3f`~~ or something.)  Edit: Eh, not that `sizeOf @Vec3f` is, itself, bad, but you wouldn't want to do that to get the size of the `vtxColor` field, in case the type of that field changes.

**Comment by achirkin** [comment]
Hmm, I stumbled upon the same problem in the [`vulkan-triangles` example](https://github.com/achirkin/vulkan/blob/abe9b65df6b776a66ca0e1a14c094b6187adf1bc/vulkan-triangles/src/Lib/Vulkan/Vertex.hs#L59-L61), but I could not come up with a nice way to add the offset info to a `PrimBytes` class.

Perhaps, I could add another class, something like
```Haskell
class PrimBytes t => PrimByteField (name :: Symbol) t where
  offsetOf :: t -> Int
```
Then, I could add a generic-deriving mechanics for the record types too.
Sounds like a good exercise on `Generics`! :)

UPDATE:
The class defined above would require writing the `deriving` declaration for every record. Doesn't look very handy. Need to think of something a bit smarter.

**Comment by achirkin** [comment]
Done via [Numeric.PrimBytes](https://github.com/achirkin/easytensor/blob/f9b7415d1646b3c58084d58ff4b68486b5fedcb7/easytensor/src/Numeric/PrimBytes.hs#L304-L308)!
The examples are available in [Numeric.PrimBytesTest](https://github.com/achirkin/easytensor/blob/f9b7415d1646b3c58084d58ff4b68486b5fedcb7/easytensor/test/Numeric/PrimBytesTest.hs#L294-L310) and in [vulkan-triangles](https://github.com/achirkin/vulkan/blob/30b8f21ed6575263adae2ba819a8cea67f0ebbe4/vulkan-triangles/src/Lib/Vulkan/Vertex.hs#L56).
