### ISSUE TITLE
cabal files missing

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/fasttensor#17]
I don't see cabal files for easytensor anymore, so I can't build it.  I'm guessing they're optional when using stack?  Problem is that I don't use stack.

**Comment by achirkin** [comment]
Welcome back! Yes, I am using [`hpack`](https://github.com/sol/hpack) tool to generate cabal files from `package.yaml` files. `stack` runs `hpack` automatically when you ask it to build the project, but you can build `hpack` with cabal  (or download binary, or integrate it with nix :) and run it manually.

NB: I am working on easytensor actively these days and not 100% sure the current version works with vulkan-examples out of the box, but the hackage version I think should be ok.

**Comment by Rotaerk** [comment]
I see...  Yeah I can get hpack easily using Nix, and I can use it to generate the .cabal file.  However, I'm having trouble thinking of how this should fit into my development/build process.

Basically, in my project, I have a git submodule pointing to easytensor.  I could generate the .cabal file there, but since I can't commit them, I'm going to have to manually re-generate the .cabal files for every easytensor project every time I clone my project or something.  Also, I don't think there are any hooks in cabal that will allow me to auto-generate the .cabal files at build time.  Basically, it seems like this is forcing me to choose between always manually generating the cabal files (i.e. my project doesn't build out-of-the-box), or adding another build tool (e.g. switching to stack, or maybe using shake) just to handle the auto-generation of the .cabal.

Do you have any suggestions as to how this can be addressed?  Or could you perhaps return to including the .cabal files in your git repo, for the people who use cabal directly?

**Comment by achirkin** [comment]
Hmm, since you are using nix, can you add some kind of nix hook to call hpack on build?
Otherwise, you can use the hackage version of easytensor - it surely contains the cabal file.
I can upload a new version to hackage if you need.

Personally I don't like to keep both package.yaml and cabal file, because it means duplicating the same information. And I sometimes forget to commit the changes in the cabal file -- this would break the project for cabal users, and I even would not notice it while using hpack.

**Comment by Rotaerk** [comment]
I don't use Nix to build my project anymore.  It was a nightmare to resolve dependencies through nixpkgs (cabal is so much better at solving the right combination of package versions), and it was slow to build (it rebuilt my entire project every time, rather than just the changed modules).  Now I just use a nix-shell to provide me my tools (e.g. ghc, cabal, vulkan-tools) and any non-haskell dependencies (e.g. libGL, vulkan-loader, xorg), and use the cabal v2 commands to build my project and run a REPL.  (With the v2 commands, I don't see any point in using stack.)

I have for the time being pointed my project to the hackage version of easytensor (and it does build against the latest vulkan-api).  I suppose I just need to keep in mind that, if I'm going to use easytensor in a submodule, I need to manually generate the cabal files.
