### ISSUE TITLE
slice and ewfoldr usage

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/fasttensor#18]
I'm trying to understand how to use the DataFrame operations, and need some help.

What I specifically need for my code right now is, given a `Vector VkMemoryHeap 16`, I need to get the first N elements of that vector (determined at runtime).  Then I need to filter them using a predicate.  Then of the remaining ones, I need to sum their `getField @"size"`values.

I used to do this by converting the Vector to a list, and then just use standard list operations, but the `toList` function is no longer exported by easytensor.

I was looking at `slice`, because it seems relevant, and I can't make sense of what it's trying to do, or how to use it.

**Comment by Rotaerk** [comment]
Actually, I stared at the signature of `slice` for a while, and thought through some concrete examples, and I think I "get it" now...  `bd` is the size of the slice in the sliced dimension, and `bi` is the number of such slices in that dimension, so if `b'` is the total size of that dimension, then `bi` = `b' + 1 - bd`.

Thus, given the signature:
```hs
slice ::
  forall (bi :: Nat) (bd :: Nat) (b' :: Nat) (bs' :: [Nat]).
  (b' ~ ((bi + bd) - 1), bs ~ (b' :+ bs'), KnownDim bd) =>
  Idxs (as +: bi) -> DataFrame t asbs -> DataFrame t (bd :+ bs')
```

If I have a `Vector VkMemoryHeap 16` and I want to get a slice containing the first 8 elements, then:
- `asbs` =`'[16]`
- `as` = `'[]`
- `bs` = `'[16]`
- `b'` = `16`
- `bs'` = `'[]`
- `bd` = `8`
- `bi` = `9`

So I need to do something like:  `slice (Idx @9 0 :* U) memoryHeaps`.  (I haven't tested this yet.)

But since I need the size of the slice to be determined at runtime, I'm not sure how that would work.

**Comment by achirkin** [comment]
First of all, `easytensor` is all about type-ensured safety, so the compiler must know the sizes of the original space (`b'`), the index space (`bi`), and the new space (`bd`). You've read the signature correctly. Thus, to use this function you need to provide these type variables with actual values (either numeric literals or some `KnownDim` variables).

Now, here is the problem. `slice` function was always a disaster. See, it works very nice when you can type exact dimension sizes as numbers, and compiler can check the safety constraint `bi ~ (b' + 1 - bd)` as `9 ~ (16 + 1 - 8)`. But if one or more of the variables are not static (i.e. `KnownDim n => n`), GHC often cannot prove that the constraint is satisfied. There are some compiler plugins that solve this problem (e.g. [`ghc-typelits-natnormalise`](http://hackage.haskell.org/package/ghc-typelits-natnormalise)) and I plan to include one in `easytensor` soon. But for now, using this function can be very clumsy. For example, I used slicing in an implementation of [mergesort](https://github.com/achirkin/easytensor/blob/v2/easytensor/src/Numeric/Subroutine/Sort.hs#L150-L218) for DataFrames. There, I use a lot of `sameDim` and `plusDim`/`minusDim` and alike to prove that the constraints are satisfied and necessary `KnownDim` evidence is available.

Back to your question. I can think of a few ways to solve the problem:

  * Use `slice` function. Then, I'd suggest to wrap `Vector VkMemoryHeap 16` into an `XFrame`, so it has type `DataFrame VkMemoryHeap '[N 16]` or `DataFrame VkMemoryHeap '[XN m]`, where `m` is some minimal required number (e.g. 0). Then, you sliced vectors would have type  `DataFrame VkMemoryHeap '[XN 0]` and you would have to pattern match against them (`XFrame`) to get the actual `KnownDim n` sizes at runtime.
  * You can go the old way by converting the `DataFrame` into a list by using function `ewfoldr @VkMemoryHeap @'[_] @'[] (:) []` (read as "element-wise foldr"). NB: there is a simple `sewfoldr` function (read as "simple element-wise foldr") in github repo, but not on hackage yet. It requires much less `TypeApplications`.
  * It looks like the whole processing you need can be done in a single `iwfoldr` (read as "index-wise foldr") or another fold type, something like this:
  ```Haskell
  getSome maxN cond = iwfoldr @VkMemoryHeap @'[_] @'[]
      (\(Idx i :* U) x s -> if i < maxN && cond x then (s + getField @"size" x) else s) 0
  ```

NB: Generally, `Numeric.DataFrame.SubSpace` functions is all you need for all kinds of DataFrame processing. All functions are very flexible, but require TypeApplications. The main thing to remember when using them is that the first three type parameters are always the [Element type, indexing subspace (as), element subspace (bs)]. Often you just need to specify the length of the dimension lists, and you can use wildcards.

**Comment by Rotaerk** [comment]
Hmm thanks, that should get me going.

It looks like the fold approach should be pretty straight forward.  The main problem with it, though, is that it necessarily iterates over _all_ elements in the vector, even if you only care about the first N.  So I will try your suggestion for how to use `slice` to first cut those out, and then perform a fold.

In case you're curious why I'm doing this, it's because Vulkan sometimes defines data types, such as [VkPhysicalDeviceMemoryProperties](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPhysicalDeviceMemoryProperties.html), containing arrays along with a count of how many elements within the array are actually used.

Here's where I was originally doing this with the DF.toList function: 
 https://github.com/Rotaerk/vulkanTest/blob/master/sandbox/sandbox/src/Main.hs#L707-L712

**Comment by achirkin** [comment]
Yes, it iterates through all elements in the current hackage version, but this is only because the fold is strict there. In the new version I have both lazy and strict versions of folds, so you can use `take n . ewfoldr (:) []` /  `take n . ewfoldl (flip (:)) []` to get first `n` elements on the left/right side of the frame lazily.

**Comment by Rotaerk** [comment]
Ah cool.  In that case, I will just use the fold, and replace it later once v2 is ready.

**Comment by Rotaerk** [comment]
I'm trying again to slice something based on a runtime-determined length, and I'm not really clear on how to do it...

I know that if I want the first n elements of `v :: Vector t m`, I can do `sslice @_ @_ @_ @n (Idx 0) xd`.  I could also do `sslice (Idx @(m - n + 1)) v`, but while it's more convenient in terms of type argument order, it's less convenient in specifying slice length.

But if the length is not known until runtime, I still don't see how that would work...

The use-case this time is that if I have two `Vector t m`, I want to check than their first n elements are equal.  Since DataFrame already has an Eq instance, I figured I could slice them to length n and then just check if the slices are equal.  But in the meantime I'm resorting to folding both dataframes to lists, taking the first N of those lists, and checking that the lists are equal.

**Comment by achirkin** [comment]
If you are using lazy left fold (`ewfoldl`) to create the intermediate lists, GHC should be able to optimize them out in your use case (please let me know if you notice this is not the case).

If you want to do this via slicing, you can go two ways. But in either case, you would need to create a type-level dim.

  * Heavy-typed way:
    1. Create a new dim: `case someDimVal n of Dx (D :: Dim n) -> _`; in the scope of this `case` expression, `n` is a `KnownDim` variable.
    2. Prove that `SubFrameIndexCtx m (m - n + 1) n`; this can be cumbersome until I implement a proper type-checker plugin for `dimensions` (like [here](https://github.com/achirkin/easytensor/blob/3ef88ab3bfc095d131365a588fe3282a2be5d0c1/easytensor/src/Numeric/Subroutine/Sort.hs#L162-L167))
    3. Use one of the approaches you suggested to slice.

  * Less-typed way: wrap everything into `XNat`, and you don't need to prove GHC anything. You can also use `ssliceMaybe` that does not throws out-of-bounds errors.
```Haskell
case someDimVal n of
    Dx (D :: Dim n) -> ssliceMaybe @_ @(XN 0) @(XN 0) @(N n) (Idx 0) (XFrame v)
```

**Comment by Rotaerk** [comment]
Interesting.  It took me some staring and thinking, but I think I get it.  Thanks!

**Comment by Rotaerk** [comment]
Figured it out:
```hs
prefEqual :: forall t (s :: Nat). (Eq t, PrimBytes t, KnownDim s) => Word -> Vector t s -> Vector t s -> Maybe Bool
prefEqual prefixLen v1 v2 =
  case someDimVal prefixLen of
    Dx p@(D :: Dim p) -> -- prefix length is now a KnownDim
      case minusDimM s p of
        Just smp@D -> -- (s - p) is now a KnownDim
          case plusDim smp D1 of
            smp1@D -> -- (s - p + 1) is now a KnownDim
              case sameDim (plusDim s D1) (plusDim smp1 p) of
                Just Dict -> -- (s + 1) ~ (s - p + 1 + p), aka SubFrameIndexCtx s (s - p + 1) p, is now in scope.
                  let
                    idx = proxyIdx 0 smp1
                  in
                    Just (sslice idx v1 == sslice idx v2)
                _ -> Nothing
        _ -> Nothing
  where
    s = D @s
    proxyIdx :: forall (x :: Nat) proxy. BoundedDim x => Word -> proxy x -> Idx x
    proxyIdx w _ = Idx w
```

That was a fun learning exercise, but I don't think I want that to be the implementation I check-in to my codebase :)

**Comment by achirkin** [comment]
Yeah, it's not pretty :(
One thing that could ease the burden a bit is `MonadFail Maybe`. Something like this (not checked):
```Haskell
prefEqual :: forall t (s :: Nat). (Eq t, PrimBytes t, KnownDim s) => Word -> Vector t s -> Vector t s -> Bool
prefEqual prefixLen v1 v2 = fmap (True ==) $ do
  Dx p@(D :: Dim p) <- pure $ someDimVal prefixLen -- prefix length is now a KnownDim
  smp@D <- minusDimM (D @s) p -- (s - p) is now a KnownDim
  smp1@D <- pure $ plusDim smp D1 -- (s - p + 1) is now a KnownDim
  Dict <- sameDim (plusDim (D @s) D1) (plusDim smp1 p)  -- (s + 1) ~ (s - p + 1 + p), aka SubFrameIndexCtx s (s - p + 1) p, is now in scope.
  return $ sslice @_ @_ @(s - p + 1) 0 v1 == sslice @_ @_ @(s - p + 1) 0 v2
```
I also use pattern guard syntax sometimes, but GHC often fails to recognize complete patterns (if they make use of GADTs) and issues lots of warnings.

**Comment by Rotaerk** [comment]
What's this "type-checker plugin" you mentioned?  How would that work?  What would it look like?

**Comment by achirkin** [comment]
I plan to implement something like [ghc-typelits-natnormalise](https://hackage.haskell.org/package/ghc-typelits-natnormalise), for `KnownDim`, `Nat`, `XNat`, and `TypeList`. Basically, the plugin should derive constraints for you based on int/list arithmetics rules.

**Comment by Rotaerk** [comment]
Neat!
