### ISSUE TITLE
packDF usage?

### ISSUE THREAD

**Issue by Rotaerk** [achirkin/fasttensor#19]
The following works:
```hs
myVector :: DataFrame Double '[4]
myVector =
  packDF @Double @4 @'[] 1 2 3 4
```

The following doesn't type-check
```hs
vertices :: DataFrame Vertex '[4]
vertices =
  packDF @Vertex @4 @'[]
    (Vertex (vec3 0 0 0) (vec2 0 0))
    (Vertex (vec3 0 0 0) (vec2 0 0))
    (Vertex (vec3 0 0 0) (vec2 0 0))
    (Vertex (vec3 0 0 0) (vec2 0 0))

data Vertex =
  Vertex {
    vtxPos :: Vec3f,
    vtxTexCoord :: Vec2f
  } deriving (Eq, Show, Generic)

instance PrimBytes Vertex
```

The error is:
```
    • Couldn't match type ‘DataFrame Vertex '[]’ with ‘Vertex’
      Expected type: Vertex
                     -> Vertex -> Vertex -> Vertex -> DataFrame Vertex '[4]
        Actual type: PackDF Vertex '[] 4 (DataFrame Vertex '[4])
    • The expression ‘packDF @Vertex @4 @'[]’
      is applied to four arguments,
      but its type ‘PackDF Vertex '[] 4 (DataFrame Vertex '[4])’ has none
      In the expression:
        packDF
          @Vertex
          @4
          @'[]
          (Vertex (vec3 0 0 0) (vec2 0 0))
          (Vertex (vec3 0 0 0) (vec2 0 0))
          (Vertex (vec3 0 0 0) (vec2 0 0))
          (Vertex (vec3 0 0 0) (vec2 0 0))
      In an equation for ‘vertices’:
          vertices
            = packDF
                @Vertex
                @4
                @'[]
                (Vertex (vec3 0 0 0) (vec2 0 0))
                (Vertex (vec3 0 0 0) (vec2 0 0))
                (Vertex (vec3 0 0 0) (vec2 0 0))
                (Vertex (vec3 0 0 0) (vec2 0 0))
    |
295 |       packDF @Vertex @4 @'[]
```
Why?

**Comment by Rotaerk** [comment]
Oh I see... it requires the arguments to be DataFrames, and I guess Doubles count as DataFrames for some reason?  I got it to work like:

```hs
vertices :: DataFrame Vertex '[4]
vertices =
  packDF @Vertex @4 @'[]
    (S $ Vertex (vec3 0 0 0) (vec2 0 0))
    (S $ Vertex (vec3 0 0 0) (vec2 0 0))
    (S $ Vertex (vec3 0 0 0) (vec2 0 0))
    (S $ Vertex (vec3 0 0 0) (vec2 0 0))
```

**Comment by Rotaerk** [comment]
Now I tried making a helper method:
```hs
vertexDF = S .: Vertex
```
And it actually compiles *unless* I annotate its type.  If I give it a type-hole, like:
```hs
vertexDF :: _
```
The compiler says:
```
    • Found type wildcard ‘_’
        standing for ‘Vec2f -> Vec2f -> DataFrame Vertex '[]’
      To use the inferred type, enable PartialTypeSignatures
    • In the type signature: vertexDF :: _
    |
370 | vertexDF :: _
    |             ^
```
But when I give it the signature it suggests:
```hs
vertexDF :: Vec2f -> Vec2f -> DataFrame Vertex '[]
vertexDF = S .: Vertex
```
It gives me:
```
    • Couldn't match type ‘Nat’ with ‘*’
      Expected type: Vec2f -> Vec2f -> DataFrame Vertex '[]
        Actual type: Vec2f -> Vec2f -> DataFrame Vertex '[]
      Use -fprint-explicit-kinds to see the kind arguments
    • In the expression: S .: Vertex
      In an equation for ‘vertexDF’: vertexDF = S .: Vertex
    |
370 | vertexDF = S .: Vertex
    |            ^^^^^^^^^^^
```

Edit: Ah! I need to explicitly specify the kind of `'[]` as `[Nat]`, then it works...  Alternatively, I can just replace `DataFrame Vertex ('[] :: [Nat])` with `Scalar Vertex`.

**Comment by achirkin** [comment]
Yeah, `packDF` isn't one of the simple functions :) A few notes:

  * `packDF` is basically a helper function for creating DataFrame constructors (pattern synonyms). I have defined first eight of them `DF2` .. `DF9`. These are generally very easy to use and do not require TypeApplications.
  * Both `packDF` and constructors take DataFrames as arguments, not primitive elements! Thus, if you want to create a vector, you type something like `DF5 (S ..) (S .. ) ..`; If you want to create a matrix, you type `DF5 ((DF6 (S ..) ..) .. `.
  * The exception for the above is the instances of `Num`: All fixed-size DataFrames are instances of `Num`, if the element type is also `Num`; hence you can use literals and omit `S` constructor. The first type parameter `packDF` and `DFx` is the element type, not the sub-dataframe type.
  * The ('[] :: [k]) problem is the tricky one. DataFrames and Dims can be indexed by `Nat` and `XNat`, so they don't force the kind of the dimension list. As a result, GHC cannot determine kind of the list if it is empty. The exception is `S :: t -> DataFrame t ('[] :: [Nat])` constructor - it forces the list to be `Nat`-indexed.

Please, ask more questions! I am trying to write a tutorial and need some view from outside.
