### ISSUE TITLE
Hello, Artem Chirkin. I have some question for easytensor.

### ISSUE THREAD

**Issue by ubuntunux** [achirkin/fasttensor#27]
Hi, I am developing Vulkan in Haskell using easytensor and vulkan-api library.

Thank you for your contribution.

If vulkan-api and easytensor do not exist, Haskell's vulkan programming is not possible.

But easytensor is so hard for me to understanding... and English too.. T_T

I have a question.

I want to get pure List from XFrame as below but I had failed..

dataFrameToList :: DataFrame Vec3f (xns::[XNat]) -> [Vec3f]

Can you help me? Let me know how can I convert XFrame to List.

And I want to know how to apply map function to XFrame.

I will wait for your answer. Thank you.

And I hope more easy examples about easytensor.

Below are some of my project and easytensor notes.

https://github.com/ubuntunux/HulkanEngine3D
https://github.com/ubuntunux/PyEngine3D
https://wikidocs.net/47790

**Comment by achirkin** [comment]
Hi, thanks for your interest!

First of all, [`Vec3f`](http://hackage.haskell.org/package/easytensor-2.1.0.0/docs/Numeric-Vector.html#t:Vec3f) is just a synonym for `DataFrame Float '[3]`. So you have here a nested DataFrame, normally, a preferred solution would be to have something like `DataFrame Float '[XN k, N 3]` (reads as "an array of 3D vectors, that has length of at least `k`"), or more general `DataFrame Float (xns +: N 3)`. Though, you can always flatten nested DataFrames using [`joinDataFrame`](http://hackage.haskell.org/package/easytensor-2.1.0.0/docs/Numeric-DataFrame-SubSpace.html#v:joinDataFrame). But of course, you can surely use a nested DataFrame too.

Regarding your question, I don't remember if easytensor has this exact function, but you can make one using folds. For example, you can use [`sewfoldr`](http://hackage.haskell.org/package/easytensor-2.1.0.0/docs/Numeric-DataFrame-SubSpace.html#v:sewfoldr), which reads as "simple element-wise right fold". That is, just like with a normal `Foldable`, you can write `dataFrameToList = sewfoldr (:) []` to construct a lazy list (or `sewfoldr (\x xs -> unScalar x : xs) []` for a nested DataFrame).
The [`Numeric.DataFrame.SubSpace`](http://hackage.haskell.org/package/easytensor-2.1.0.0/docs/Numeric-DataFrame-SubSpace.html) module has a set of very flexible folds, maps, and traversals, which work with arbitrary dimensionalities (known or unknown at compile time). However, you may need to use lots of type annotations to fix the types (which makes it rather difficult use in the beginning).

**Comment by ubuntunux** [comment]
Thank you very much.
