### ISSUE TITLE
export convenience contraints for >1 KnownDim and Dimensions

### ISSUE THREAD

**Issue by stites** [achirkin/fasttensor#3]
dimensions-1.0 is excellent and has removed all of the helpers I've written for hasktorch. The remnants of these are just `KnownDim<N>` and `Dimensions<N>` convenience constraints since we are prioritizing statically typed tensors, and we wind up with a high number of these one-off constraints (I've only gotten up to 2d auto differentiable convolution, and I've found `KnownDim5` fairly useful). Would this be something that you might consider adding to `dimensions`?

**Comment by achirkin** [comment]
Thanks! It is pleasure to see someone finds it useful :)

I'm going to [ZuriHac 2018](https://2018.zurihac.info/) this weekend, so maybe can add that.
Though, I am not sure what you mean by `KnownDim<N>` convenience constraints:  `KnownDim<N>` implies `N` is known at compile time (in other words it is a `Nat` literal); `KnownDim` should be resolved via `KnownNat` automatically in that case. If it is not resolved automatically, could you please show me a code snippet? maybe, this is a bug.
The more interesting case is `Dimensions<N>`; we could add something like `type Dimensions3 a b c = Dimensions '[a,b,c]`. Is that what you mean? And if not, would this definition be of some use?

**Comment by achirkin** [comment]
Ahh, I got your point while searching `KnownDim<N>` in hasktorch repo.

So, wouldn't [`All`](https://hackage.haskell.org/package/dimensions-1.0.0.0/docs/Numeric-Type-List.html#t:All) work for this purpose? E.g. :
```
type KnownDim4 a b c d = All KnownDim '[a,b,c,d]
type Dimensions3 a b c = All Dimensions '[a,b,c]
```
The RHS does not look much more complicated, and it is certainly more generic; so would you just use that?

**Comment by stites** [comment]
Yes! That's genius and way more flexible! Hasktorch is my first attempt at a dependently-typed API, so apologies for any trivial questions like this. I may have more since so far we have been using `dimensions` but haven't gotten into actual dependently-typed transformations like squeeze/unsqueeze.

Thank you @achirkin ! Closing this now.
