### ISSUE TITLE
ghc-8.6

### ISSUE THREAD

**Issue by tonyday567** [achirkin/fasttensor#7]
prepping for ghc-8.6, following https://gist.github.com/DanBurton/43b5f5155fdd1affd02f6e86f37da9ae, I get:

```
/Users/tonyday/haskell/easytensor/dimensions/src/Numeric/Dim.hs:65:44: error: parse error on input ‘*’
       |
    65 |   , Nat, CmpNat, type (+), type (-), type (*), type (^)
       |                                            ^
```
Some sort of interaction between * and Type perhaps?

**Comment by tonyday567** [comment]
https://ghc.haskell.org/trac/ghc/wiki/Migration/8.6#StarIsType

**Comment by achirkin** [comment]
Thanks! Qualified imports should work; added in commit 4dc8f46.

It compiles for me now, but please re-open the issue if necessary.

**Comment by tonyday567** [comment]
awesome, thanks
